(SETQ ISOMCLOSURE (CONS (FUNCTION CAR) (QUOTE ISOMCLOSURE)))
(SETQ ISOM (QUOTE %ISOM))
(SETQ DUMMY (QUOTE %DUMMY))
(SETQ EMPTY (QUOTE %EMPTY))
(SETQ NILL (QUOTE %NIL))
(SETQ TZERO
      (QUOTE
       (NIL (CAR (CAAR (CAAAR (CAAAAR) (CDAAAR)) (CDAAR (CADAAR) (CDDAAR)))
		 (CDAR (CADAR (CAADAR) (CDADAR)) (CDDAR (CADDAR) (CDDDAR))))
	    (CDR (CADR (CAADR (CAAADR) (CDAADR)) (CDADR (CADADR) (CDDADR)))
		 (CDDR (CADDR (CAADDR) (CDADDR)) (CDDDR (CADDDR) (CDDDDR)))))))